# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      # Fails if there are any ">>>>>" lines in files due to merge conflicts.
      - id: check-merge-conflict
      # Trims trailing whitespace. Allow a single space on the end of .md lines for hard line breaks.
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      # Makes sure files end in a newline and only a newline;
      - id: end-of-file-fixer
      # Attempts to load all TOML files to verify syntax.
      - id: check-toml
      # Attempts to load all yaml files to verify syntax; unsafe: only check syntax, do not load yaml
      - id: check-yaml
        args: ["--unsafe"]
      # Fail if staged files are above a certain size.
      # To add a large file, use 'git lfs track <file>; git add <file> to track large files with
      # git-lfs rather than commiting them directly to the git history
      - id: check-added-large-files
        args: ["--maxkb=500"]

        # HALT! Before you exclude a large file and commit it, forever
        # bloating our repo size, did you:
        # (1) use a CLI tool like imageoptim to compress them if they are images
        # (2) think hard about whether using DVC or git-lfs is more appropriate
        #     for the file--such as in the case of CSV files or other data
        # This can be confusing. Reach out for help in our chat to help decide
        # how to deal adding these large files you have :)
      # Sort requirements in requirements.txt files.
      - id: requirements-txt-fixer
      # Prevent committing directly to trunk (since Bitbucket wants us to pay for this feature)
      - id: no-commit-to-branch
        args: ["--branch=main"]
      # Detects the presence of private keys
      - id: detect-private-key

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: "v0.0.287"
    hooks:
      - id: ruff
        args: [--exit-non-zero-on-fix, --config=./pyproject.toml]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v1.5.1"
    hooks:
      - id: mypy
        args:
          [
            --no-strict-optional,
            --config-file=./pyproject.toml,
          ]

  - repo: https://github.com/psf/black
    rev: 23.9.0
    hooks:
      - id: black
        args:
          - --config=./pyproject.toml

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args:
          - --settings-path=./pyproject.toml

  - repo: https://github.com/numpy/numpydoc
    rev: v1.6.0rc2
    hooks:
      - id: numpydoc-validation

  - repo: https://github.com/nbQA-dev/nbQA
    rev: 1.7.0
    hooks:
      - id: nbqa-black
      - id: nbqa-isort
      - id: nbqa-mypy
      - id: nbqa-ruff
        types_or: [jupyter, markdown]
